//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwaMe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MetricsBySwathColumns {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetricsBySwathColumns() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwaMe.Properties.MetricsBySwathColumns", typeof(MetricsBySwathColumns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgMzRange.
        /// </summary>
        public static string AvgMzRange {
            get {
                return ResourceManager.GetString("AvgMzRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scansPerSwath.
        /// </summary>
        public static string scansPerSwath {
            get {
                return ResourceManager.GetString("scansPerSwath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swathNumber.
        /// </summary>
        public static string swathNumber {
            get {
                return ResourceManager.GetString("swathNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwathProportionOfTotalTIC.
        /// </summary>
        public static string SwathProportionOfTotalTIC {
            get {
                return ResourceManager.GetString("SwathProportionOfTotalTIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swAvgProportionSinglyCharged.
        /// </summary>
        public static string swAvgProportionSinglyCharged {
            get {
                return ResourceManager.GetString("swAvgProportionSinglyCharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swDensityAverage.
        /// </summary>
        public static string swDensityAverage {
            get {
                return ResourceManager.GetString("swDensityAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swDensityIQR.
        /// </summary>
        public static string swDensityIQR {
            get {
                return ResourceManager.GetString("swDensityIQR", resourceCulture);
            }
        }
    }
}
